node:
  build: .
  ports:
    - "82:80"
  volumes:
    - ./app:/app
    - ./files:/files
    - ./tmp_files:/tmp_files
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  env_file: .dockerenv
  restart: always

nginx:
  image: nginx
  volumes:
     - ./files:/usr/share/nginx/html/thumbs:ro
  ports:
     - "80:80"